- name: playbook environment
  hosts: "{{servidor_1}}"
  become: yes
  become_user: root
  tasks:
  - name: copy docker-compose.yml 
    copy:
      src: docker-compose.yml
      dest: ejemplo_ansible/
  #creamos el archivo .env para variables de entorno
  - name: create and copy file .env
    copy: 
      dest: ejemplo_ansible/.env
      content: 
        PORT="{{puerto}}"
        version="{{num_version}}"
        version_web="{{version_num}}"
  - name: test docker-compose with .env
    shell:
      cmd: "sudo docker-compose up -d"
      chdir: ejemplo_ansible/