---
- hosts: "{{server1}}"
  become: yes
  tasks:
  - name: copy file
    ansible.builtin.copy:
      src: uubuntu/example.txt
      dest: /home/debian/example.txt
      owner: uubuntu
      group: uubuntu
      mode: '0644'
