---
    - name: install policy ssh ftp web
      hosts: 192.168.43.90
      become: yes
      tasks:
        - name: accept service ssh dmz to mz
          ansible.builtin.iptables:
            chain: FORWARD
            protocol: tcp
            destination_port: 22
            source: 10.10.10.2
            destination: 20.20.20.2
            jump: ACCEPT

        - name: accept service ssh mz to dmz
          ansible.builtin.iptables:
            chain: FORWARD
            protocol: tcp
            destination_port: 22
            source: 20.20.20.2
            destination: 10.10.10.2
            jump: ACCEPT

        - name: accept service web dmz to mz
          ansible.builtin.iptables:
            chain: FORWARD
            protocol: tcp
            destination_port: 80
            source: 10.10.10.2
            destination: 20.20.20.2
            jump: ACCEPT

        - name: accept service web mz to dmz
          ansible.builtin.iptables:
            chain: FORWARD
            protocol: tcp
            destination_port: 80
            source: 20.20.20.2
            destination: 10.10.10.2
            jump: ACCEPT     

        - name: accept service web dmz to mz
          ansible.builtin.iptables:
            chain: FORWARD
            protocol: tcp
            destination_port: 80
            source: 10.10.10.2
            destination: 20.20.20.2
            jump: ACCEPT

        - name: accept service ftp 
          ansible.builtin.iptables:
            chain: FORWARD
            protocol: tcp
            destination_port: 20
            source: 20.20.20.2
            destination: 10.10.10.2
            jump: ACCEPT   

        - name: accept service ftp 
          ansible.builtin.iptables:
            chain: FORWARD
            protocol: tcp
            destination_port: 21
            source: 20.20.20.2
            destination: 10.10.10.2
            jump: ACCEPT  

        - name: accept service ftp 
          ansible.builtin.iptables:
            chain: FORWARD
            protocol: tcp
            destination_port: 20
            source: 10.10.10.2
            destination: 20.20.20.2
            jump: ACCEPT   

        - name: accept service ftp 
          ansible.builtin.iptables:
            chain: FORWARD
            protocol: tcp
            destination_port: 21
            source: 10.10.10.2
            destination: 20.20.20.2
            jump: ACCEPT    