---
- hosts: 10.132.32.166
  become: yes
  tasks:
    - name: permit service ssh dmz to mz
      ansible.builtin.iptables:
        chain: FORWARD
        protocol: tcp
        destination_port: 22
        source: 10.10.10.2
        destination: 20.20.20.2
        jump: ACCEPT
    
    - name: permit service ssh mz to dmz
      ansible.builtin.iptables:
        chain: FORWARD
        protocol: tcp
        source_port: 22
        source: 20.20.20.2
        destination: 10.10.10.2
        jump: ACCEPT
