---
- hosts: 192.168.43.85
  become: yes
  gather_facts: false
  tasks:
    - name: "add repository 1"
      ansible.builtin.apt_repository:
        repo: "deb http://www.deb-multimedia.org buster main non-free"
        state: present
    - name: "add repository 2"
      ansible.builtin.apt_repository:
        repo: "hola mundo"
        state: present