---
- gather_facts: false
  hosts: 192.168.43.85
  become: yes
  
  tasks:
    - name: "add repository 1"
      ansible.builtin.apt_repository:
        repo: "deb-scr http://deb.debian.org/debian/ buster-updates main"
        state: present
   
