---
- hosts: 192.168.43.85
  become: yes
  
  tasks:
    - name: "add repository 1"
      ansible.builtin.apt_repository:
        repo: "deb http://www.deb-multimedia.org buster main non-free"
        state: present
   
